### ISSUE TITLE
Time stamp is not updating correctly for each Reporter.log step 

### ISSUE THREAD

**Issue by rajasekharbora** [email2vimalraj/TestNGExtentsReport#4]
Hi Vimal, Thanks for your listener which make easy way for creating report. 
I am running the following code as Maven project, Extent report generating is generating, but Timestamp is not updating properly for each Reporter.log step.

package test;

import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;

import java.io.IOException;

/**
 * This is a sample TestNG test.
 */
public class TestNgTest {
    @AfterMethod
    public void afterMethod(ITestResult iTestResult) throws IOException {
        Reporter.log("After Method: " + iTestResult.getMethod().getMethodName());
    }

    @Test(groups = {"group1"})
    public void simpleTest() {
    	Reporter.log("Simple test", true);
        Reporter.log("Simple test");
        Reporter.log("Another log");
    }

    @Test(groups = {"group2"})
    public void anotherSimpleTest() {
        Reporter.log("Another Simple test");
    }
}

Timestamp is same for all the steps shown in below.

Status	Timestamp	Details
info_outline	3:32:50 PM	Simple test
info_outline	3:32:50 PM	Simple test
info_outline	3:32:50 PM	Another log
check_circle	3:32:50 PM	Passed

**Comment by email2vimalraj** [comment]
@rajasekharbora : That is because all the reporter output are gathered at the end of method execution and creating the info message out of it. So the timestamp that you are noticing is the one when creating the info message. This is a limitation on the TestNG, since we can't listen to the Reporter.log() event. Hence this cannot be fixed.
